### ISSUE TITLE
Material Dashboard Preset

### ISSUE THREAD

**Issue by teamupdivision** [laravel-frontend-presets/internals#10]
Hello @m1guelpf, @OwenMelbz,

We implemented another fronted preset with our partners [Creative Tim](https://www.creative-tim.com/) for [Material Dashboard](https://www.creative-tim.com/product/material-dashboard). The preset is done and ready to be published. Here is the link to the repo [https://github.com/updivision/material-dashboard](https://github.com/updivision/material-dashboard)

Regards
Alin

**Comment by OwenMelbz** [comment]
:) I’m currently out of action, so hopefully m1guelpf can help!

I don’t suppose you know if @tabacitu plans to integrate any of these with Backpack?

**Comment by m1guelpf** [comment]
Can you transfer the repo to the organization? After that's done, I'll give you admin access to the repo when it's done :)

**Comment by teamupdivision** [comment]
> :) I’m currently out of action, so hopefully m1guelpf can help!
> 
> I don’t suppose you know if @tabacitu plans to integrate any of these with Backpack?

@OwenMelbz  He has no plans to integrate them with Backpack as far as I know. Would be nice to have  Backpack Frontend Presets right? We will think about that.

Regards,
Alin

**Comment by teamupdivision** [comment]
> Can you transfer the repo to the organization? After that's done, I'll give you admin access to the repo when it's done :)

@m1guelpf can you publish it on packagist? You can close the issue after. Thank you!

Alin

**Comment by m1guelpf** [comment]
Done!
