### ISSUE TITLE
Black Dashboard Preset

### ISSUE THREAD

**Issue by teamupdivision** [laravel-frontend-presets/internals#12]
Hello @m1guelpf

We implemented another fronted preset with our partners Creative Tim for Material Dashboard. The preset is done and ready to be published. Here is the link to the repo https://github.com/updivision/material-dashboard

Regards
Alin

**Comment by Ghitu** [comment]
Hello @m1guelpf 

Did you receive my previous message?

Regards
Alin

**Comment by m1guelpf** [comment]
Hey! Feel free to transfer the repo and I'll add you as an admin and add it to Packagist

**Comment by Ghitu** [comment]
Hello @m1guelpf 

I transferred the repository. It is [https://github.com/laravel-frontend-presets/black-dashboard](https://github.com/laravel-frontend-presets/black-dashboard).

Regards
Alin

**Comment by Ghitu** [comment]
Hello @OwenMelbz,

Can you please help us?

Regards
Alin

**Comment by m1guelpf** [comment]
@Ghitu I've added both you and @teamupdivision as admins and added the package to Packagist, let me know if there's anything else that should be done.
