### ISSUE TITLE
White-dashboard, now-ui-dashboard, light-bootstrap-dashboard presets

### ISSUE THREAD

**Issue by teamupdivision** [laravel-frontend-presets/internals#13]
Hello @m1guelpf

We implemented some fronted presets with our partners Creative Tim. The presets are done and ready to be published. Here are the links to the repos
https://github.com/laravel-frontend-presets/white-dashboard-laravel (can you rename it to white-dashboard? thanks)
https://github.com/laravel-frontend-presets/white-dashboard-laravel (can you rename it to white-dashboard? thanks)
https://github.com/laravel-frontend-presets/light-bootstrap-dashboard
https://github.com/laravel-frontend-presets/now-ui-dashboard

Regards
Alin

**Comment by m1guelpf** [comment]
@teamupdivision I've renamed the first one and added the first two to Packagist, but the third is missing required package.json info, could you fix that up?

**Comment by teamupdivision** [comment]
Thanks @m1guelpf 
I updated the composer.json with correct info

Regards,
Alin

**Comment by teamupdivision** [comment]
Hi @m1guelpf , 
I transferred another repository. The preset is done and ready to be published.
https://github.com/laravel-frontend-presets/paper-dashboard

Thanks

**Comment by m1guelpf** [comment]
Added both to Composer :tada:
