### ISSUE TITLE
W3CSS Preset

### ISSUE THREAD

**Issue by superjoefly** [laravel-frontend-presets/internals#4]
I've written a W3CSS preset for Laravel, set it up on composer to test it and it seems to be working fine. I had to change the composer.json and the name of the folder to avoid conflicts with this repo, but everything else is as suggested per the Readme. I mostly used the Bulma preset as a guide for development. Can you guys check it out, test it and let me know if there's anything I need to change? I'm also wondering what the next steps would be to add it to this repo. Thanks :-)

EDIT:

I made a few changes to some of the files, including the composer.json and README.md. Hopefully the changes will make it easier to migrate. The repo is [here](https://github.com/superjoefly/w3css). Just let me know if there is anything that needs to be changed, or if I can help with the migration...
Thanks :-)

**Comment by deeshrestha** [comment]
Hi,

We have added you as maintainer on packagist. I think you should be able to submit your package with proper namespace.

By the way seems like `bulma` is not included on your `updatePackageArray` function.
`Arr::except($packages, ['bootstrap-sass', 'foundation-sites', 'uikit', 'bulma']);`

My personal idea is to make easier to switch between known presets (during initial setup if you change your mind) without resetting with `preset-none` coz we might want to keep the JS preset intact while switching between CSS presets or vice versa.

@m1guelpf @OwenMelbz I have added the skeleton on Packagist so that we can add the maintainers there to give access to namespace.

**Comment by superjoefly** [comment]
@Laraveldeep @m1guelpf @OwenMelbz 

I added 'bulma' to the `updatePackageArray` function ...

I'm confused about how to submit the repo to packagist...

While testing, I used the repo from my own github account, and submitted the package using the url to that repo. I'm not sure how to submit a package using a different url. Does it need to be forked over first?

Can you advise me on how to add it?

Sorry, I'm new at this...

Thanks for your help :-)

**Comment by m1guelpf** [comment]
@superjoefly It's very easy. You just have to edit your composer.json file and change the vendor namespace (vendornamespace/packagename) to  the one we use at the organization

**Comment by superjoefly** [comment]
@Laraveldeep @m1guelpf @OwenMelbz 

Okay, I'm still not sure if I did that right... :-/

I used the url to the package (w3css) in my own github account, which was `https://github.com/superjoefly/w3css`, to submit the package to Packagist.

I tried using `https://github.com/laravel-frontend-presets/w3css` for the url, but it didn't work because the package doesn't exist at that url.

Did I do this correctly?

Just let me know if I need to change something.

Thanks :-)

**Comment by deeshrestha** [comment]
@superjoefly I have sent you invitation to join the org. Move your repo here and maintain it here before you publish on Packagist.

**Comment by superjoefly** [comment]
Awe shucks!

I just release it...probably as you were typing...

Can I still move it over?

By the way...it's been on Packagist for almost two weeks now...but only as dev-master.

**Comment by deeshrestha** [comment]
I guess so. If possible kindly re-link the package from new repo. Will be easier for all I guess :) Thanks!

**Comment by m1guelpf** [comment]
@Laraveldeep If you move ot to the org, maybe we can do some :sparkles: with packagist...

**Comment by superjoefly** [comment]
I forked it over to the organization and updated the link on Packagist.

Now I'm just trying to set up the github web-hook for updates.

I hope I'm doing this right...Please, let me know if I need to change anything. :-)

**Comment by deeshrestha** [comment]
@superjoefly our repos are created here linked to packagist from here. I guess you can do same. Just have to create new one here, move it and link. I am not sure what you are trying to do.

**Comment by deeshrestha** [comment]
@m1guelpf please suggest

**Comment by m1guelpf** [comment]
@superjoefly I'd suggest to transfer the repo instead of the fork, it'll make everything easier

**Comment by superjoefly** [comment]
I already forked it over to the organization, and changed the link on packagist to the repo in the organization. It is currently present in the organization, and I tested via composer require. It passed...
Is this correct?

**Comment by OwenMelbz** [comment]
Hey, did you guys got this sorted?

**Comment by superjoefly** [comment]
As far as I know, everything is working as it should.
If there's anything that I need to change, please let me know.

Thanks guys :-)

**Comment by m1guelpf** [comment]
@superjoefly Everything is working, thank you!
