### ISSUE TITLE
Add Karma-ESLint as a frontend preset

### ISSUE THREAD

**Issue by MohannadNaj** [laravel-frontend-presets/internals#5]
Hello Everyone

Thanks for this project, I like it, I like the idea of the presets, and kinda confused about why it's not used as much as I expected it.

____

[Repo Link: laravel-karma-eslint-preset](https://github.com/MohannadNaj/laravel-karma-eslint-preset)

I just published this preset: https://github.com/MohannadNaj/laravel-karma-eslint-preset

Originally I wanted it to be from the start at your organization, but before publishing I got confused about the procedure/steps should be taken for this merge, that's why I [renamed it in the last moment](https://github.com/MohannadNaj/laravel-karma-eslint-preset/commit/a55b0983843597984faffebdc8244236dd058f83) and [published it to packagist](https://packagist.org/packages/mohannadnaj/laravel-karma-eslint-preset), this way it will be easier for you to test it and see it in action.

## What is it?

a frontend preset that will merge nicely with the default laravel application, to power it with a ready to use javascript unit testing  & code coverage & linting tools.

The chosen tests runner is Karma, and the code coverage tool is istanbul -through `karma-coverage`-, and the linting tool is ESLint Airbnb style guide.

## Motivation

At least in my experience, it's always painful to set this up every time and get it to work with laravel structure without ignoring laravel-mix.

However, what got me here is: I installed a webpack template from `vuejs/vue-cli` inside my laravel project, and starting step by step trying to merge the stuff and get the best out of (the template + laravel-mix + laravel structure). Suddenly I found myself ended up with this preset.

## Pros?

- Encouraging a good habit by providing easy setup for javascript testing alongside Laravel.

- Now we care about ESLint and style guides also, Awesome :D

- Personally, I was really in need for a working frontend testing setup alongside laravel, turns out there is so many options to test and check it out before I got there.

## Cons?

- Opinionated tools: Why not `jest`? Why not `mocha-webpack`? why the `phantomjs` browser and not `jsdom`?

- Scope of usage is not promising.

- A scary warning on the initial installation of the preset for copying files confirmation:
![screenshot](https://i.imgur.com/8sXQjVb.png)

My response for this point: I couldn't workaround this, I felt it's necessary to tell the user about what's going to happen. every fresh laravel project comes already with the files: `.gitignore`,`package.json`,`resources/assets/js/components/ExampleComponent.vue`. that's means the `override it` warning will always persist.

- Insufficient Handling of package.json file.

I didn't follow the skeleton repo and the laravel way of handling package.json, in this preset I just do a whole `File::copyDirectory` for the stubs directory. including the package.json

The reason for this: Laravel doesn't offer an efficient way of rewriting different values for both `devDependencies` and `dependencies`. Laravel always writes to `devDependencies` only.

____

That being said, I totally understand if you prefer that this preset shouldn't be part of the organization account. and I will appreciate your thoughts/comments about the points mentioned above.

**Comment by m1guelpf** [comment]
@MohannadNaj I have invited you to the organization. Feell free to transfer your repository here and then we'll setup packagist for it. Thank you for your hard work!

**Comment by MohannadNaj** [comment]
Thanks @m1guelpf , just did it, and removed my packagist package and reverted the renaming commit so now it matches the organization's namespace.

https://github.com/laravel-frontend-presets/karma-eslint

if anyone curious about the transfer, [steps from github here](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization).

**Comment by m1guelpf** [comment]
@MohannadNaj I uploaded the package to Packagist and added you the @laravel-frontend-presets/karma-eslint-preset team. Everything should be good to go. Thank you for your work on this!

**Comment by MohannadNaj** [comment]
Thanks dear @m1guelpf .. 🙏 really appreciate it, my fear of criticism told me that it will never be accepted. Thanks for breaking this, and thanks for the awesome quick response & feedback.
