### ISSUE TITLE
Vuetify framework as Laravel Frontend preset

### ISSUE THREAD

**Issue by acacha** [laravel-frontend-presets/internals#7]
Hi all!

I have created a (opinionated) Laravel Frontend preset for Vuetify (https://vuetifyjs.com).

Source code is available at: https://github.com/acacha/laravel-vuetify

I also documented the steps I take at https://medium.com/@sergiturbadenas/step-by-step-tutorial-to-add-vuetify-to-laravel-with-scaffolding-auth-and-vuex-ac3f5a875bc5

Please let me know the additional steps I have to follow to publish this package.

**Comment by acacha** [comment]
@m1guelpf ping ;-)

**Comment by m1guelpf** [comment]
@acacha I'm going to invite you to the organization so you can transfer the repo. Ping me when it's done

**Comment by acacha** [comment]
@m1guelpf thanks I'll start now. One question: do you want I change also https://github.com/laravel-frontend-presets/laravel-frontend-presets.github.io to add vuetify preset?

**Comment by acacha** [comment]
@m1guelpf Ok Github repo transfered. Now I tried to add package to packagist but give me the following error:

The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at laravel-frontend-presets

**Comment by acacha** [comment]
@@m1guelpf ping. Please help me solve Packagist problem...

**Comment by m1guelpf** [comment]
@acacha Oh, sorry. I fixed it 6 days ago, but forgot to report here. Everything should be fixed now :)

**Comment by acacha** [comment]
Thanks!
