### ISSUE TITLE
Add Stimulus preset

### ISSUE THREAD

**Issue by slogsdon** [laravel-frontend-presets/internals#8]
Repo: https://github.com/slogsdon/php-laravel-preset-stimulus

This package makes it easy to use the [Stimulus](https://stimulusjs.org/) JavaScript framework with Laravel 5.5+.

**Comment by m1guelpf** [comment]
Added you to the organization, olease accept and transfer the repo

**Comment by slogsdon** [comment]
@m1guelpf Done: https://github.com/laravel-frontend-presets/stimulus

**Comment by m1guelpf** [comment]
Added to packagist

**Comment by slogsdon** [comment]
Thanks!
