### ISSUE TITLE
Add Argon Dashboard preset 

### ISSUE THREAD

**Issue by teamupdivision** [laravel-frontend-presets/internals#9]
Hello,

We created a fronted preset for [Argon Dashboard](https://www.creative-tim.com/product/argon-dashboard) free theme, form our partners [Creative Tim](https://www.creative-tim.com/), and we would like to publish it on Laravel Frontend Presets. The preset is done and ready to be published.

Let us know what are the nest steps for adding the preset to your list.

Regards,
[Alin ](https://github.com/Ghitu)

**Comment by m1guelpf** [comment]
@teamupdivision Is there a repo I can checkout?

**Comment by teamupdivision** [comment]
Hi @m1guelpf, 
We have the code on Bitbucket, at the moment, so we can give you access to the repository there. Let us know your account.

Regards,
Alin

**Comment by m1guelpf** [comment]
@teamupdivision We'd need to migrate the code to GitHub to add it to the org, are you okay with that?

**Comment by teamupdivision** [comment]
Hi @m1guelpf, @OwenMelbz,
Here is the link to the repo https://github.com/updivision/argon

Let us know what are the next steps.
Regards,
Alin

**Comment by m1guelpf** [comment]
@teamupdivision You have to go to the dashboard and init the transfer to this organization. Once it's transferred, I'll give you admin access to the repo, and add it to Packagist

**Comment by teamupdivision** [comment]
@m1guelpf Github says that to transfer repositories to an organization, I must have repository creation permissions. So I can init the transfer to you and you can add it to the organization.

Regards,
Alin

**Comment by teamupdivision** [comment]
@m1guelpf did you receive the transfer request?

**Comment by teamupdivision** [comment]
@m1guelpf @OwenMelbz 
I've made the transfer. It can be published on Packagist. 
Thanks,
Alin

**Comment by m1guelpf** [comment]
<img width="1280" alt="image 2019-01-22 at 6 59 52 pm" src="https://user-images.githubusercontent.com/23558090/51555479-f44ae000-1e77-11e9-8cce-56a43955fb07.png">
Sorry, it looks like I was too slow. Can you retry? :)

**Comment by teamupdivision** [comment]
> <img alt="image 2019-01-22 at 6 59 52 pm" width="1280" src="https://user-images.githubusercontent.com/23558090/51555479-f44ae000-1e77-11e9-8cce-56a43955fb07.png">
> 
> Sorry, it looks like I was too slow. Can you retry? :)

@m1guelpf I've already made the transfer https://github.com/laravel-frontend-presets/argon, @OwenMelbz gave me access. Can you please publish the package to packagist so I can test it out? 

Thank you
Alin

**Comment by m1guelpf** [comment]
Wow that was fast! Added to packagist. Can we close this?

**Comment by teamupdivision** [comment]
@m1guelpf Thanks. Sure, we can close this now.
